sudo: false

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export JOBS=max
  - export prebuild_compile=true

node_js:
  - "4.0"
  - "3.0"
  - "2.4"
  - "1.8"
  - "1.0"
  - "0.12"
  - "0.10"
